# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
name: Fong Fan
headshot: 'assets/images/headshot.jpg'
title: Fong Fan
email: fong.fan.dev@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Software Developer
baseurl: "" # The URL of your site
url: "http://localhost:4000/" # The URL of your site


# Layouts - Home
parallax_image_one:  https://images.unsplash.com/photo-1438401171849-74ac270044ee?auto=format&fit=crop&w=1492&q=80&ixid=dW5zcGxhc2guY29tOzs7Ozs%3D
parallax_image_two:  https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1352&q=80&ixid=dW5zcGxhc2guY29tOzs7Ozs%3D
parallax_image_three:  https://images.unsplash.com/photo-1487952307198-4ccfbfca2f80?auto=format&fit=crop&w=1055&q=80&ixid=dW5zcGxhc2guY29tOzs7Ozs%3D
parallax_image_four:  https://images.unsplash.com/photo-1491472253230-a044054ca35f?auto=format&fit=crop&w=1363&q=80&ixid=dW5zcGxhc2guY29tOzs7Ozs%3D
parallax_image_five:  https://images.unsplash.com/photo-1478812348191-a9280e039733?auto=format&fit=crop&w=1350&q=80&ixid=dW5zcGxhc2guY29tOzs7Ozs%3D

# Contact
github: https://github.com/voltaaage
linked_in: http://linkedin.com/in/fongfan
twitter_username: fongvoltfan
github_username:  voltaaage

# Collections
collections:
- experiences
- projects

# Build settings
markdown: kramdown
permalink: pretty
theme: minima
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-minifier

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

